name: daily_flutter_demo
description: Demo application showcasing use of the Daily Flutter SDK.
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

publish_to: none

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  daily_flutter: ^0.32.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.3.0
  shared_preferences: ^2.2.2
  wakelock_plus: ^1.3.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
