name: daily_flutter_demo
description: Demo application showcasing use of the Daily Flutter SDK.
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

publish_to: none

dependencies:
  collection:
  cupertino_icons:
  daily_flutter: ^0.28.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  logging:
  shared_preferences:
  wakelock_plus: ^1.2.8

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
